torneo/futbol/urls.py
from django.contrib import admin
from django.urls import include, path
from futbol.views import InsertarTorneo, InsertarCiudad, InsertarJugador, InsertarEstadio, InsertarArbitro, InsertarPersonaNatural, InsertarEquipo, InsertarEmpresa, InsertarJugadorEquipo, InsertarPartido, InsertarJugadorPartido, InsertarEventoGol, InsertarEventoFalta, InsertarOtroEvento, Home, RolArbitro
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('login/',auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='login.html'),name='logout'),
    path('RolArbitro', RolArbitro.as_view(), name="RolArbitro"),
    path('InsertarTorneo', InsertarTorneo.as_view(), name="InsertarTorneo"),
    path('InsertarCiudad', InsertarCiudad.as_view(), name="InsertarCiudad"),
    path('InsertarJugador', InsertarJugador.as_view(), name="InsertarJugador"),
    path('InsertarEstadio', InsertarEstadio.as_view(), name="InsertarEstadio"),
    path('InsertarArbitro', InsertarArbitro.as_view(), name="InsertarArbitro"),
    path('InsertarPersonaNatural', InsertarPersonaNatural.as_view(), name="InsertarPersonaNatural"),
    path('InsertarEquipo', InsertarEquipo.as_view(), name="InsertarEquipo"),
    path('InsertarEmpresa', InsertarEmpresa.as_view(), name="InsertarEmpresa"),
    path('InsertarJugadorEquipo', InsertarJugadorEquipo.as_view(), name="InsertarJugadorEquipo"),
    path('InsertarPartido', InsertarPartido.as_view(), name="InsertarPartido"),
    path('InsertarJugadorPartido', InsertarJugadorPartido.as_view(), name="InsertarJugadorPartido"),
    path('InsertarEventoGol', InsertarEventoGol.as_view(), name="InsertarEventoGol"),
    path('InsertarEventoFalta', InsertarEventoFalta.as_view(), name="InsertarEventoFalta"),
    path('InsertarOtroEvento', InsertarOtroEvento.as_view(), name="InsertarOtroEvento"),
 
]

torneo/torneo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('futbol.urls', 'futbol'), namespace='futbol')),
]

torneo/futbol/models.py
from django.db import models

class RolArbitro(models.Model):
    id = models.AutoField(
        primary_key = True
    )
    nombre = models.CharField(
        max_length = 25
    )
    @classmethod
    def create(cls, id, nombre):
        id = cls(id=id)
        nombre = cls(nombre=nombre)
        return nombre

class Pais(models.Model):
    id = models.IntegerField(
        primary_key = True
    )
    iso = models.CharField(
        max_length = 2,
        null = True
    )
    nombre = models.CharField(
        max_length = 46,
        null = True
    )

class Torneo(models.Model):
    id = models.AutoField(
        primary_key = True
    )
    nombre = models.CharField(
        max_length = 30
    )
    pais = models.ForeignKey(Pais, on_delete=models.DO_NOTHING)

class Ciudad(models.Model):
    codigo = models.AutoField(
        primary_key = True,
    )
    nombre = models.CharField (max_length=40, unique = True)
    poblacion = models.IntegerField ()
    pais = models.ForeignKey(Pais, on_delete=models.DO_NOTHING, default="1")

class Jugador(models.Model):
    codigo = models.IntegerField(
        primary_key = True,
    )
    nombre = models.CharField (max_length= 40, default="1")
    edad = models.CharField(max_length=2, default="1")

class Estadio(models.Model):
    codigo = models.IntegerField(
        primary_key = True,
    )
    nombre = models.CharField (max_length=40)
    id_ciudad = models.ForeignKey(Ciudad,on_delete = models.DO_NOTHING, default="1")
    anno_construccion = models.PositiveSmallIntegerField()
    capacidad = models.IntegerField ()

class Arbitro(models.Model):
    carne = models.IntegerField(
        primary_key = True,
    )
    nombre = models.CharField (max_length=40)
    tutor_de_arbitro = models.ForeignKey('self', on_delete = models.DO_NOTHING, default="1", null = True)
    rol = models.ForeignKey(RolArbitro, on_delete = models.DO_NOTHING, default="1")

class persona_natural(models.Model):
    cedula = models.IntegerField(
        primary_key = True,
    )
    nombre = models.CharField (max_length=40)
    telefono = models.CharField (max_length=20, default="1")

class Equipo(models.Model):
    codigo = models.IntegerField(
        primary_key = True,
    )
    ciudad = models.ForeignKey(Ciudad, on_delete = models.CASCADE)
    nombre = models.CharField (max_length=40)
    anno_creacion = models.CharField(max_length=4)
    patrocinador_equipo = models.ForeignKey('self', on_delete = models.CASCADE, default="1", null=True)
    patrocinador_persona_natural = models.ForeignKey(persona_natural, on_delete = models.CASCADE, default="1", null = True)

class Empresa(models.Model):
    codigo = models.IntegerField(
        primary_key = True,
    )
    nombre = models.CharField (max_length=40, unique = True, default="nombre_empresa")
    representante_legal = models.CharField (max_length=40)
    email = models.CharField (max_length=60)
    ciudad_sede_principal = models.ForeignKey(Ciudad, on_delete = models.DO_NOTHING, default="1")
    equipo_patrocinado = models.ForeignKey(Equipo, on_delete = models.DO_NOTHING, default="1", null = True)

class Jugador_Equipo(models.Model):
    equipo_actual = models.ForeignKey(Equipo, on_delete = models.CASCADE, related_name="jugador_equipo_equipo")
    jugador = models.ForeignKey(Jugador, on_delete = models.CASCADE)
    fecha_inicial = models.DateField()
    fecha_final = models.DateField()
    equipo_anterior = models.ForeignKey(Equipo, on_delete=models.DO_NOTHING, null = True)

class Partido(models.Model):
    arbitro = models.ForeignKey(Arbitro, on_delete = models.CASCADE, default="1")
    estadio = models.ForeignKey(Estadio, on_delete = models.CASCADE, default="1")
    equipo_local = models.ForeignKey(Equipo, on_delete = models.CASCADE, related_name='equipo_local_partido', default="1")
    equipo_visitante = models.ForeignKey(Equipo, on_delete=models.CASCADE, related_name='equipo_visitante_partido', default="1")
    fecha = models.DateField()
    hora = models.CharField(max_length=5)
    marcador = models.CharField(max_length=10)
    ganador = models.ForeignKey(Equipo, on_delete = models.CASCADE, null = True )
    empate = models.CharField(max_length = 2, default="--", null = True)
    nombre_torneo = models.ForeignKey(Torneo, on_delete=models.DO_NOTHING, default="1")

class Jugador_Partido(models.Model):
    partido = models.ForeignKey(Partido, on_delete = models.CASCADE)
    jugador = models.ForeignKey(Jugador, on_delete = models.CASCADE)
    min_ingreso = models.CharField(
        max_length = 10,
    )
    min_salida = models.CharField(
        max_length = 10,
    )

class Evento_Gol(models.Model):
    partido = models.ForeignKey(Partido, on_delete = models.CASCADE, default="1")
    minu = models.PositiveSmallIntegerField()
    seg = models.PositiveSmallIntegerField()
    Jugador_partido = models.ForeignKey(Jugador_Partido, on_delete = models.CASCADE)

class Evento_Falta(models.Model):
    partido = models.ForeignKey(Partido, on_delete = models.CASCADE)
    minu = models.PositiveSmallIntegerField()
    seg = models.PositiveSmallIntegerField()
    jugador_produjo = models.ForeignKey(Jugador_Partido, on_delete = models.CASCADE, related_name='evento_falta_golpe_jugador_produjo')
    jugador_recibio = models.ForeignKey(Jugador_Partido, on_delete = models.CASCADE, related_name='evento_falta_golpe_jugador_recibido')
    descripcion = models.CharField(max_length=100)

class Otro_Evento(models.Model):
    partido = models.ForeignKey(Partido, on_delete = models.CASCADE)
    minu = models.PositiveSmallIntegerField()
    seg = models.PositiveSmallIntegerField()
    jugador_principal = models.ForeignKey(Jugador_Partido, on_delete=models.DO_NOTHING)
    descripcion = models.CharField(
        max_length=100
    )

torneo/futbol/views.py
from django.shortcuts import render
from futbol.models import Torneo, Ciudad, Jugador, Estadio, Arbitro, persona_natural, Equipo, Empresa, Jugador_Equipo, Partido, Jugador_Partido, Evento_Gol, Evento_Falta, Otro_Evento, RolArbitro
from futbol.form import FormularioTorneo, FormularioCiudad, FormularioJugador, FormularioEstadio, FormularioArbitro, FormularioPersonaNatural, FormularioEquipo, FormularioEmpresa, FormularioJugadorEquipo, FormularioPartido, FormularioJugadorPartido, FormularioEventoGol, FormularioEventoFalta, FormularioOtroEvento, FormularioRolArbitro
from django.views.generic.edit import CreateView, DeleteView
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin


#Login

class Login (LoginRequiredMixin, generic.TemplateView):
    template_name="login.html"
    login_url = 'futbol:login'



# Inserts



class RolArbitro(LoginRequiredMixin, generic.CreateView):
    model = RolArbitro
    template_name="futbol/RolArbitro.html"
    context_object_name="obj"
    form_class=FormularioRolArbitro
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'

class InsertarTorneo(LoginRequiredMixin, generic.CreateView):
    model = Torneo
    template_name="futbol/InsertarTorneo.html"
    context_object_name="obj"
    form_class=FormularioTorneo
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'


class InsertarCiudad(LoginRequiredMixin, generic.CreateView):
    model = Ciudad
    template_name="futbol/InsertarCiudad.html"
    context_object_name="obj"
    form_class=FormularioCiudad
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'

class InsertarJugador(LoginRequiredMixin, generic.CreateView):
    model = Jugador
    template_name="futbol/InsertarJugador.html"
    context_object_name="obj"
    form_class=FormularioJugador
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'

class InsertarEstadio(LoginRequiredMixin, generic.CreateView):
    model = Estadio
    template_name="futbol/InsertarEstadio.html"
    context_object_name="obj"
    form_class=FormularioEstadio
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'

class InsertarArbitro(LoginRequiredMixin, generic.CreateView):
    model = Arbitro
    template_name="futbol/InsertarArbitro.html"
    context_object_name="obj"
    form_class=FormularioArbitro
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'

class InsertarPersonaNatural(LoginRequiredMixin, generic.CreateView):
    model = persona_natural
    template_name="futbol/InsertarPersonaNatural.html"
    context_object_name="obj"
    form_class=FormularioPersonaNatural
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'

class InsertarEquipo(LoginRequiredMixin, generic.CreateView):
    model = Equipo
    template_name="futbol/InsertarEquipo.html"
    context_object_name="obj"
    form_class=FormularioEquipo
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'

class InsertarEmpresa(LoginRequiredMixin, generic.CreateView):
    model = Empresa
    template_name="futbol/InsertarEmpresa.html"
    context_object_name="obj"
    form_class=FormularioEmpresa
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'

class InsertarJugadorEquipo(LoginRequiredMixin, generic.CreateView):
    model = Jugador_Equipo
    template_name="futbol/InsertarJugadorEquipo.html"
    context_object_name="obj"
    form_class=FormularioJugadorEquipo
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'

class InsertarPartido(LoginRequiredMixin, generic.CreateView):
    model = Partido
    template_name="futbol/InsertarPartido.html"
    context_object_name="obj"
    form_class=FormularioPartido
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'

class InsertarJugadorPartido(LoginRequiredMixin, generic.CreateView):
    model = Jugador_Partido
    template_name="futbol/InsertarJugadorPartido.html"
    context_object_name="obj"
    form_class=FormularioJugadorPartido
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'

class InsertarEventoGol(LoginRequiredMixin, generic.CreateView):
    model = Evento_Gol
    template_name="futbol/InsertarEventoGol.html"
    context_object_name="obj"
    form_class=FormularioEventoGol
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'

class InsertarEventoFalta(LoginRequiredMixin, generic.CreateView):
    model = Evento_Falta
    template_name="futbol/InsertarEventoFalta.html"
    context_object_name="obj"
    form_class=FormularioEventoFalta
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'

class InsertarOtroEvento(LoginRequiredMixin, generic.CreateView):
    model = Otro_Evento
    template_name="futbol/InsertarOtroEvento.html"
    context_object_name="obj"
    form_class=FormularioOtroEvento
    success_url=reverse_lazy("futbol:home")
    login_url = 'futbol:login'


# Consults

class Home(LoginRequiredMixin, generic.ListView):
    model = Partido
    template_name="futbol/Home.html"
    context_object_name="obj"
    login_url = 'futbol:login'

torneo/futbol/templates/futbol/Home.html
{% extends 'base/base.html'%}
{% load static %}
{% block contenido %}

<div class="row">

    <div class="col-sm-5 left" style="line-height:0; display:block; display:inline-block; top: -200px; z-index:1;">
        <img src="{% static 'images/izquierda.png'%}" alt="">
    </div>

    <div class="col-sm-2" style="z-index:2;">
        <div class="login-box">
            <img src="{% static 'images/balon1.png'%}" class="avatar" alt="Avatar Image">
            <h1>Home</h1>
            <tr>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarTorneo' %}">Crear Torneo</a></td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarPartido' %}">Crear Partido</a></td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarCiudad' %}">Registrar Ciudad</a></td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarEstadio' %}">Registrar Estadio</a></td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:RolArbitro' %}">Crear Rol Arbitro</a></td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarArbitro' %}">Crear Arbitro</a></td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarJugador' %}">Crear Jugador</a></td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarEquipo' %}">Crear Equipo</a></td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarJugadorEquipo' %}">Conectar Jugador con
                        un equipo</a></td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarJugadorPartido' %}">Asignar Jugador a
                        Partido</a></td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarEventoGol' %}">Registrar Gol</a></td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarEventoFalta' %}">Registrar Falta</a>
                </td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarOtroEvento' %}">Registrar evento de
                        partido</a></td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarPersonaNatural' %}">Registrar Persona
                        Natural</a></td>
                <td><a class="btn btn-primary tcol" href="{% url 'futbol:InsertarEmpresa' %}">Registrar Empresa</a></td>
            </tr>
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <a class="btn btn-warning tcol move" href="{% url 'futbol:logout'%}">Cerrar sesión</a>
                </div>
            </div>
        </div>
    </div>

    <div class="col-sm-5 right"
        style="line-height:0; display:block; display:inline-block; top: -200px; left: -510px; z-index: 1;">
        <img src="../../static/images/derecha.png" alt="">
    </div>

</div>

<div class="row">

    <div class="col-sm-1 left">
    </div>

    <div class="col-sm-10" style="z-index:2; top: -480px;">


        <table class="table">

            <tr>
                <th>ID</th>
                <th>Torneo</th>
                <th>Arbitro</th>
                <th>Estadio</th>
                <th>Local</th>
                <th>Visitante</th>
                <th>Fecha</th>
                <th>Hora</th>
                <th>Marcador</th>
                <th>Ganador</th>
                <th>Empate</th>
            </tr>

            {% for item in obj%}
            <tr>
                <td>{{item.id}}</td>
                <td>{{item.nombre_torneo}}</td>
                <td>{{item.arbitro}}</td>
                <td>{{item.estadio}}</td>
                <td>{{item.equipo_local}}</td>
                <td>{{item.equipo_visitante}}</td>
                <td>{{item.fecha}}</td>
                <td>{{item.hora}}</td>
                <td>{{item.marcador}}</td>
                <td>{{item.ganador}}</td>
                <td>{{item.empate}}</td>
            </tr>
            {% endfor %}

        </table>


        <div class="col-sm-1 right">
        </div>

    </div>

    {% endblock %}

torneo/futbol/templates/futbol/InsertarArbitro.html
{% extends 'base/base.html'%}

{% block contenido %}

<div class="row">

  <div class="col-sm-5 left" style="line-height:0; display:block; display:inline-block; top: -200px; z-index:1;">
    <img src="../../static/images/izquierda.png" alt="">
  </div>

  <div class="col-sm-2" style="z-index:2;">
    <div class="login-box">
      <img src="../../static/images/balon1.png" class="avatar" alt="Avatar Image" href="{% url 'futbol:home' %}">
      <h1>Crear Arbitro</h1>
      <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Registrar">
      </form>
      <div class="col-md-2">
        <a class="btn btn-warning" href="{%  url 'futbol:home' %}">Home</a>
      </div>
    </div>
  </div>

  <div class="col-sm-5 right"
    style="line-height:0; display:block; display:inline-block; top: -200px; left: -510px; z-index: 1;">
    <img src="../../static/images/derecha.png" alt="">
  </div>

</div>
{% endblock %}

torneo/futbol/templates/futbol/InsertarCiudad.html
{% extends 'base/base.html'%}

{% block contenido %}

<div class="row">

  <div class="col-sm-5 left" style="line-height:0; display:block; display:inline-block; top: -200px; z-index:1;">
    <img src="../../static/images/izquierda.png" alt="">
  </div>

  <div class="col-sm-2" style="z-index:2;">
    <div class="login-box">
      <img src="../../static/images/balon1.png" class="avatar" alt="Avatar Image">
      <h1>Registrar Ciudad</h1>
      <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Registrar">
      </form>
      <div class="col-md-2">
        <a class="btn btn-warning" href="{%  url 'futbol:home' %}">Home</a>
      </div>
    </div>
  </div>

  <div class="col-sm-5 right"
    style="line-height:0; display:block; display:inline-block; top: -200px; left: -510px; z-index: 1;">
    <img src="../../static/images/derecha.png" alt="">
  </div>

</div>
{% endblock %}

torneo/futbol/templates/futbol/InsertarEmpresa.html
{% extends 'base/base.html'%}

{% block contenido %}

<div class="row">

  <div class="col-sm-5 left" style="line-height:0; display:block; display:inline-block; top: -200px; z-index:1;">
    <img src="../../static/images/izquierda.png" alt="">
  </div>

  <div class="col-sm-2" style="z-index:2;">
    <div class="login-boxx">
      <img src="../../static/images/balon1.png" class="avatar" alt="Avatar Image">
      <h1>Regístrar Empresa</h1>
      <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Registrar">
      </form>
      <div class="col-md-2">
        <a class="btn btn-warning" href="{%  url 'futbol:home' %}">Home</a>
      </div>
    </div>
  </div>

  <div class="col-sm-5 right"
    style="line-height:0; display:block; display:inline-block; top: -200px; left: -510px; z-index: 1;">
    <img src="../../static/images/derecha.png" alt="">
  </div>

</div>
{% endblock %}

torneo/futbol/templates/futbol/InsertarEquipo.html
{% extends 'base/base.html'%}

{% block contenido %}

<div class="row">

  <div class="col-sm-5 left" style="line-height:0; display:block; display:inline-block; top: -200px; z-index:1;">
    <img src="../../static/images/izquierda.png" alt="">
  </div>

  <div class="col-sm-2" style="z-index:2;">
    <div class="login-boxx">
      <img src="../../static/images/balon1.png" class="avatar" alt="Avatar Image">
      <h1>Crear Equipo</h1>
      <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Registrar">
      </form>
      <div class="col-md-2">
        <a class="btn btn-warning" href="{%  url 'futbol:home' %}">Home</a>
      </div>
    </div>
  </div>

  <div class="col-sm-5 right"
    style="line-height:0; display:block; display:inline-block; top: -200px; left: -510px; z-index: 1;">
    <img src="../../static/images/derecha.png" alt="">
  </div>

</div>
{% endblock %}

torneo/futbol/templates/futbol/InsertarEventoFalta.html
{% extends 'base/base.html'%}

{% block contenido %}

<div class="row">

  <div class="col-sm-5 left" style="line-height:0; display:block; display:inline-block; top: -200px; z-index:1;">
    <img src="../../static/images/izquierda.png" alt="">
  </div>

  <div class="col-sm-2" style="z-index:2;">
    <div class="login-boxx">
      <img src="../../static/images/balon1.png" class="avatar" alt="Avatar Image">
      <h1>Regístrar Falta</h1>
      <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Registrar">
      </form>
      <div class="col-md-2">
        <a class="btn btn-warning" href="{%  url 'futbol:home' %}">Home</a>
      </div>
    </div>
  </div>

  <div class="col-sm-5 right"
    style="line-height:0; display:block; display:inline-block; top: -200px; left: -510px; z-index: 1;">
    <img src="../../static/images/derecha.png" alt="">
  </div>

</div>
{% endblock %}

torneo/futbol/templates/futbol/InsertarEventoGol.html
{% extends 'base/base.html'%}

{% block contenido %}

<div class="row">

  <div class="col-sm-5 left" style="line-height:0; display:block; display:inline-block; top: -200px; z-index:1;">
    <img src="../../static/images/izquierda.png" alt="">
  </div>

  <div class="col-sm-2" style="z-index:2;">
    <div class="login-box">
      <img src="../../static/images/balon1.png" class="avatar" alt="Avatar Image">
      <h1>Regístrar Gol</h1>
      <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Registrar">
      </form>
      <div class="col-md-2">
        <a class="btn btn-warning" href="{%  url 'futbol:home' %}">Home</a>
      </div>
    </div>
  </div>

  <div class="col-sm-5 right"
    style="line-height:0; display:block; display:inline-block; top: -200px; left: -510px; z-index: 1;">
    <img src="../../static/images/derecha.png" alt="">
  </div>

</div>
{% endblock %}

torneo/futbol/templates/futbol/InsertarJugadorEquipo.html
{% extends 'base/base.html'%}

{% block contenido %}

<div class="row">

  <div class="col-sm-5 left" style="line-height:0; display:block; display:inline-block; top: -200px; z-index:1;">
    <img src="../../static/images/izquierda.png" alt="">
  </div>

  <div class="col-sm-2" style="z-index:2;">
    <div class="login-boxx">
      <img src="../../static/images/balon1.png" class="avatar" alt="Avatar Image">
      <h1>Conectar Jugador con Equipo</h1>
      <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Registrar">
      </form>
      <div class="col-md-2">
        <a class="btn btn-warning" href="{%  url 'futbol:home' %}">Home</a>
      </div>
    </div>
  </div>

  <div class="col-sm-5 right"
    style="line-height:0; display:block; display:inline-block; top: -200px; left: -510px; z-index: 1;">
    <img src="../../static/images/derecha.png" alt="">
  </div>

</div>
{% endblock %}

torneo/futbol/templates/futbol/InsertarJugadorPartido.html
{% extends 'base/base.html'%}

{% block contenido %}

<div class="row">

  <div class="col-sm-5 left" style="line-height:0; display:block; display:inline-block; top: -200px; z-index:1;">
    <img src="../../static/images/izquierda.png" alt="">
  </div>

  <div class="col-sm-2" style="z-index:2;">
    <div class="login-box">
      <img src="../../static/images/balon1.png" class="avatar" alt="Avatar Image">
      <h1>Asignar Jugador a Partido</h1>
      <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Registrar">
      </form>
      <div class="col-md-2">
        <a class="btn btn-warning" href="{%  url 'futbol:home' %}">Home</a>
      </div>
    </div>
  </div>

  <div class="col-sm-5 right"
    style="line-height:0; display:block; display:inline-block; top: -200px; left: -510px; z-index: 1;">
    <img src="../../static/images/derecha.png" alt="">
  </div>

</div>
{% endblock %}

torneo/futbol/templates/futbol/InsertarOtroEvento.html
{% extends 'base/base.html'%}

{% block contenido %}

<div class="row">

  <div class="col-sm-5 left" style="line-height:0; display:block; display:inline-block; top: -200px; z-index:1;">
    <img src="../../static/images/izquierda.png" alt="">
  </div>

  <div class="col-sm-2" style="z-index:2;">
    <div class="login-boxx">
      <img src="../../static/images/balon1.png" class="avatar" alt="Avatar Image">
      <h1>Regístrar Evento de Partido</h1>
      <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Registrar">
      </form>
      <div class="col-md-2">
        <a class="btn btn-warning" href="{%  url 'futbol:home' %}">Home</a>
      </div>
    </div>
  </div>

  <div class="col-sm-5 right"
    style="line-height:0; display:block; display:inline-block; top: -200px; left: -510px; z-index: 1;">
    <img src="../../static/images/derecha.png" alt="">
  </div>

</div>
{% endblock %}